"""Mapping of Japanese CSV column headers to normalized English keys."""

FIELD_MAP: list[tuple[str, str, str]] = [
    ("serial", "シリアル", "row serial number"),
    ("store_name", "店舗名", "store / business display name"),
    ("store_name_furigana", "店舗名フリガナ", "store name reading (katakana)"),
    ("postal_code", "郵便番号", "postal code"),
    ("address_prefecture", "店舗住所（都道府県）", "address: prefecture"),
    ("address_city", "店舗住所（市区町村）", "address: city"),
    ("address_town", "店舗住所（町名）", "address: town"),
    ("address_street", "店舗住所（番地）", "address: street number"),
    ("address_building", "店舗住所（建物名）", "address: building name"),
    ("phone", "店舗電話番号", "phone number"),
    ("business_account_name", "ビジネスアカウント名", "business account name"),
    ("website_url", "ビジネスプロフィールのサイトURL", "business website url"),
    ("reference_url", "お客様情報参考サイトURL", "reference site url"),
    ("opening_date", "開業日", "opening date"),
    ("employees", "従業員数", "number of employees"),
    ("capital", "資本金", "capital"),
    ("keyword_category", "キーワード(ビジネスカテゴリー)", "business category keywords"),
    ("keyword_service", "キーワード(サービス)", "service keywords"),
    ("google_mb_owned", "info Biz Googleマイビジネスアカウントの所持", "has google business account"),
    ("owner_authority", "オーナー権限", "owner authority"),
    ("owner_contact_name", "オーナー権限所有者名・担当者名", "owner contact name"),
    ("owner_contact_info", "オーナー権限所有者・担当者連絡先", "owner contact info"),
    ("business_type", "業態", "business format / type (e.g. restaurant, IT company)"),
    ("business_hours", "info Biz営業時間", "business hours"),
    ("lunch", "info Bizランチ", "lunch hours"),
    ("dinner", "info Bizディナー", "dinner hours"),
    ("entry_time", "info Biz入店可能時間", "entry possible time"),
    ("order_time", "info Biz注文可能時間", "order possible time"),
    ("plan", "info Bizプラン", "subscription plan"),
    ("has_facebook", "info Biz Facebookアカウントの所持", "has facebook account"),
    ("has_instagram", "info Biz Instagramアカウントの所持", "has instagram account"),
    ("citation", "サイテーション", "citation"),
    ("s_plan_cms", "Sプラン CMS", "S plan CMS"),
    ("owlet_cms", "Owlet CMS", "Owlet CMS"),
    ("onerank_cms", "Onerank CMS", "Onerank CMS"),
    ("facebook_username", "info Biz Facebookユーザー名", "facebook username"),
    ("facebook_password", "info Biz Facebookパス", "facebook password"),
    ("instagram_username", "info Biz Instagramユーザー名", "instagram username"),
    ("instagram_password", "info Biz Instagramパス", "instagram password"),
    ("instagram_login_confirmed", "info Biz Instagramアカウントのログイン確認", "instagram login confirmed"),
    ("owner_authority_grant", "オーナー権限付与", "owner authority grant"),
    ("gmb_contact_time", "GMB連絡が取りやすい時間帯", "gmb preferred contact time"),
    ("gmb_contact_time_other", "GMB連絡が取りやすい時間帯【その他】", "gmb preferred contact time (other)"),
    ("gmb_contact_day", "GMB連絡が取りやすい曜日", "gmb preferred contact day"),
    ("gmb_contact_day_other", "GMB連絡が取りやすい曜日【その他】", "gmb preferred contact day (other)"),
    ("ext_link_application", "info Biz外部リンク申し込み", "external link application"),
    ("citation_existing_serial", "サイテーション既存シリアル", "existing citation serial"),
    ("gbp_multilingual", "GBPインバウンド多言語対策", "GBP inbound multilingual"),
    ("language_selection", "言語選択", "site language selection"),
    ("meo_existing_serial", "MEO既存シリアル", "existing MEO serial"),
    ("info_biz_apply", "info Biz申し込み", "info Biz application"),
    ("keyword_prefecture", "キーワード_都道府県", "keyword: prefecture"),
    ("keyword_city", "キーワード_市区町村", "keyword: city"),
    ("keyword_area_1", "キーワード_通称エリア名1", "keyword: area alias 1"),
    ("keyword_area_2", "キーワード_通称エリア名2", "keyword: area alias 2"),
    ("keyword_area_3", "キーワード_通称エリア名3", "keyword: area alias 3"),
    ("main_industry_service", "業種やサービス_メイン", "main industry / service"),
    ("sub_industry_service_1", "業種やサービス_サブ1", "sub industry / service 1"),
    ("sub_industry_service_2", "業種やサービス_サブ2", "sub industry / service 2"),
    ("sub_industry_service_3", "業種やサービス_サブ3", "sub industry / service 3"),
    ("sub_industry_service_4", "業種やサービス_サブ4", "sub industry / service 4"),
    ("keyword_notes", "キーワード備考", "keyword notes"),
    ("citation_plan", "サイテーションプラン", "citation plan"),
    ("shared_notes", "共有事項", "shared notes"),
    ("meo_premium_apply", "MEOプレミアム強化プランの申し込み", "MEO premium application"),
    ("google_ads_apply", "Google広告申し込み", "google ads application"),
    ("google_review_display", "Google口コミ表示", "google review display"),
    ("review_heading", "口コミ表示の見出し名", "review heading"),
    ("id", "ID", "id"),
    ("reservation_system", "予約システム", "reservation system"),
    ("portal_posting_apply", "ポータルサイト掲載の申し込み", "portal posting application"),
    ("google_account_id", "GoogleアカウントID", "google account id"),
    ("google_account_password", "GoogleアカウントPASS", "google account password"),
    ("replace_gbp", "既存GBP削除し、新規作成希望", "replace existing GBP"),
    ("existing_seo_subscription", "既存SEOサブスク契約有無", "existing SEO subscription"),
    ("seo_subscription_serial", "SEOサブスク既存シリアル", "SEO subscription serial"),
]

ATTRIBUTE_FIELDS: list[tuple[str, str]] = [
    (f"attribute_{i}", f"属性{i}") for i in range(1, 12)
]

ALL_FIELDS: list[tuple[str, str, str]] = FIELD_MAP + [
    (key, header, "free-form attribute") for key, header in ATTRIBUTE_FIELDS
]

HEADER_TO_KEY: dict[str, str] = {header: key for key, header, _ in ALL_FIELDS}

SENSITIVE_KEYS: set[str] = {
    "facebook_password",
    "instagram_password",
    "google_account_password",
    "facebook_username",
    "instagram_username",
    "google_account_id",
}