"""SiteSpec Contract for BBS-CMS AI Pre-Builder.

This module defines the formal contract between AI_AGENT_1 (spec generator)
and AI_AGENT_2 (content generator). The SiteSpec schema is the stable
interface that both agents depend on.

Version: 1.0.0 (see app.contracts.version.CONTRACT_VERSION)

Contract Stability: STABLE
- Breaking changes require major version bump
- New optional fields can be added in minor versions
- Consumers (AI_AGENT_2) should handle missing optional fields gracefully
"""

from __future__ import annotations

from app.contracts.version import CONTRACT_VERSION, SUPPORTED_VERSIONS
from app.schemas import (
    SiteSpec,
    SitePage,
    SiteSection,
    SiteSectionField,
    BusinessProfile,
    Criteria,
)

__all__ = [
    "SiteSpec",
    "SitePage",
    "SiteSection",
    "SiteSectionField",
    "BusinessProfile",
    "Criteria",
    "CONTRACT_VERSION",
    "SUPPORTED_VERSIONS",
]

# Contract metadata for documentation and validation
CONTRACT_METADATA = {
    "name": "BBS-CMS SiteSpec",
    "version": CONTRACT_VERSION,
    "supported_versions": SUPPORTED_VERSIONS,
    "description": "Website structure specification generated by AI_AGENT_1 and consumed by AI_AGENT_2",
    "producer": "AI_AGENT_1",
    "consumer": "AI_AGENT_2",
    "format": "JSON",
    "schema": "Pydantic (SiteSpec)",
}